- name: Ensure packages
  become: true
  apt:
    pkg:
      - curl
      - unzip
      - zip
    state: present
    update_cache: true

- name: Ensure dirs
  file:
    path:
      - "{{ download_dir }}"
      - "{{ sdkman_dir }}"
    recurse: true
    state: directory

- name: Is sdkman already installed?
  stat:
    path: "{{ sdkman_dir }}/bin/sdkman-init.sh"
  register: has_sdkman
  failed_when: false
  changed_when: false

- name: Install sdkman if needed
  when: not has_sdkman.stat.exists
  block:
    - name: Download sdkman
      become: false
      get_url:
        url: "https://get.sdkman.io"
        dest: "{{ download_dir }}/install-sdkman.sh"
        mode: 0755
    - name: Run installer
      shell: "{{ download_dir }}/install-sdkman.sh"
      environment:
        SDKMAN_DIR: "{{ sdkman_dir }}"
      args:
        executable: bash

- name: Install SDKs
  shell: |
    . {{ sdkman_dir }}/bin/sdkman-init.sh
    sdk install {{ item.sdk }} {{ item.version }}
  register: sdk_installed
  changed_when: "'already installed' not in sdk_installed.stdout"
  args:
    executable: bash
  environment:
    SDKMAN_DIR: "{{ sdkman_dir }}"
  with_items:
    - { sdk: 'java', version: "{{ java_version }}"}
    - { sdk: 'sbt', version: "" }
    - { sdk: 'scala', version: "{{ scala_version }}"}

- name: Remove installer
  file:
    path: "{{ download_dir }}/install-sdkman.sh"
    state: absent
