---
- name: Setup dev environment
  hosts: devmachine
  vars_prompt:
    - name: ssh_passphrase
      prompt: Enter your ssh key passphrase?
  vars:
    home_dir: "{{ ansible_env.HOME }}"
    java_version: "11.0.12.7.1-amzn"  # corretto
    scala_version: "2.13.8"
    dotfiles: "{{ lookup('env', 'XDG_CONFIG_HOME', default='~/.config') }}/dotfiles"
    is_desktop: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"
  roles:
    - { role: common, become: yes }
    - { role: zsh, become: no, tags: [ 'dev', 'zsh' ] }
    - { role: ssh, become: no, tags: [ 'dev', 'ssh' ] }
    - { role: python, become: no, tags: [ 'dev', 'python' ] }
    - { role: docker, become: yes, tags: [ 'dev', 'docker' ] }
    - { role: aws, become: yes, tags: [ 'dev', 'aws' ]}
    - { role: nodejs, become: yes, tags: [ 'dev', 'js' ] }
    - { role: terraform, become: yes, tags: [ 'dev', 'tf' ] }
    - { role: desktop, become: yes, tags: [ 'desktop' ], when: "(is_desktop is defined) and (is_desktop|length>0)"}
  tasks:
    - name: link gitconfig
      file:
        src: "{{ dotfiles }}/.gitconfig"
        dest: "~/.gitconfig"
        state: link
      become: false

    - name: Install sdkman and jvm
      shell: |
        curl -s "https://get.sdkman.io" | bash
        . "{{ home_dir }}/.sdkman/bin/sdkman-init.sh"
        sdk install java {{ java_version }}
        sdk install sbt
        sdk install scala {{ scala_version}}
      become: false
      args:
        executable: /bin/bash
    - debug: msg="Current user {{ ansible_env.USER }}"