- name: Install latest base packages
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - curl
    - emacs
    - git
    - libssl-dev
    - openssl
    - wget
    - gawk
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - lsb-release
    - gnupg
    - unzip
    - tar
    - zip

- name: Upgrade and cleanup
  become: true
  apt:
    upgrade: yes
    autoclean: yes
    autoremove: yes
