
- name: Download nvm
  become: false
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/install_nvm.sh
    mode: 0755
  register: download

- name: Run installer
  shell: |
    source install_nvm.sh
    source $HOME/.nvm/nvm.sh
    nvm install --lts
  args:
    chdir: /tmp
  when: download.changed

- name: Check nodejs
  shell: nodejs --version
  register: check_nodejs
  failed_when: check_nodejs.rc != 0