- name: Ensure package required by nvm
  become: true
  apt:
    pkg: curl
    state: present

- name: Ensure dirs
  file:
    path:
      - "{{ download_dir }}"
      - "{{ nvm_dir }}"
    recurse: true
    state: directory

- name: nvm is installed
  stat:
    path: "$NVM_DIR/nvm.sh"
  register: has_nvm
  failed_when: false
  changed_when: false
  environment:
    NVM_DIR: "{{ nvm_dir }}"

- name: Install nvm
  when: not has_nvm.stat.exists
  block:
  - name: Download nvm
    become: false
    get_url:
      url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
      dest: "{{ download_dir }}/install-nvm.sh"
      mode: 0755
  - name: Run installer
    shell: "{{ download_dir }}/install-nvm.sh"
    args:
      executable: /bin/bash
    environment:
      NVM_DIR: "{{ nvm_dir }}"

- name: Install nodejs
  shell: |
    . $NVM_DIR/nvm.sh
    nvm install --lts
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  register: node_installed
  changed_when: "'already installed' not in node_installed.stderr"

- name: Remove installer
  file:
    path: "{{ download_dir }}/install-nvm.sh"
    state: absent
