- name: Ensure package required by nvm
  become: true
  apt:
    pkg: curl
    state: present

- name: Ensure dirs
  file:
    path:
      - "{{ download_dir }}"
    recurse: true
    state: directory

- name: nvm is installed
  shell: "{{ shell }} -elc 'nvm --version'"
  register: has_nvm
  failed_when: false
  changed_when: false

- name: Install nvm
  when: has_nvm.rc != 0
  block:
  - name: Download nvm
    get_url:
      url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
      dest: "{{ download_dir }}/install-nvm.sh"
      mode: 0755
  - name: Run installer
    shell: "{{ shell }} -elc '{{ download_dir }}/install-nvm.sh'"

- name: Install nodejs
  shell: "{{ shell }} -elc 'nvm install --lts'"
  register: node_installed
  changed_when: "'already installed' not in node_installed.stderr"

- name: Remove installer
  file:
    path: "{{ download_dir }}/install-nvm.sh"
    state: absent
