
- name: Download nvm
  become: false
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/install_nvm.sh
    mode: 0755

- name: Run installer
  shell: |
    . install_nvm.sh
    . ~/.nvm/nvm.sh
    nvm install --lts
  args:
    chdir: /tmp

- name: Check nodejs
  shell: nodejs --version
  register: check_nodejs
  failed_when: check_nodejs.rc != 0