
- name: Download nvm
  become: false
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/install_nvm.sh
    mode: 0755

- name: Run installer
  shell: . ./install_nvm.sh
  args:
    chdir: /tmp
    executable: /bin/bash

- name: Install nodejs
  shell: |
    . ./nvm.sh
    nvm install --lts
  args:
    chdir: "{{ home_dir }}/.nvm"
    executable: /bin/bash    

- name: Check nodejs
  shell: |
    . ./nvm.sh
    node --version
  args:
    chdir: "{{ home_dir }}/.nvm"
    executable: /bin/bash
  register: check_nodejs
  failed_when: check_nodejs.rc != 0