---

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    ansible_user: "ansible"
  tasks:
    - name: "Include shell"
      include_role:
        name: "shell"
    - name: Check facts
      assert:
        that:
          - shell is defined
          - shell|length > 0