- name: has_conda
  stat:
    path: "{{ conda_dir }}/bin/conda"
  register: has_conda

- name: Install conda
  when: not has_conda.stat.exists
  become: false
  block:
  - name: Download Miniconda
    get_url:
      url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest: /tmp/install-miniconda.sh
      checksum: sha256:78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689
      mode: 0755

  - name: Create conda folder
    file:
      path: "{{ conda_dir }}"
      state: directory
      mode: 0755
      recurse: yes

  - name: Run the installer
    shell: |
      /tmp/install-miniconda.sh -b -u -p {{ conda_dir }}
      {{ conda_dir }}/bin/conda init

- name: has_gh
  stat:
    path: "{{ conda_dir }}/bin/gh"
  register: has_gh

- name: Install Github CLI
  become: false
  shell: ./bin/conda install -y -c conda-forge gh
  args:
    chdir: "{{ conda_dir }}"
  when: not has_gh.stat.exists

- name: Configure pip
  become: false
  shell: |
    ./bin/pip3 config set global.trusted-host 'pypi.org pypi.python.org files.pythonhosted.org'
  args:
    chdir: "{{ conda_dir }}"
  register: pip_conf
  failed_when: pip_conf.rc != 0
  changed_when: false

- name: Install venv (for poetry)
  apt:
    name: python3-venv
    state: present
  become: true

- name: has_poetry
  shell: |
    PATH=~/.local/bin:~/.poetry/bin:$PATH && poetry --version
  register: has_poetry
  failed_when: false
  changed_when: false

- name: Install poetry
  when: has_poetry.rc != 0
  become: false  
  block:
  - name: Download poetry
    get_url:
      url: https://install.python-poetry.org
      dest: /tmp/install-poetry.py
      mode: 0755  
  - name: Run installer
    shell: python3 /tmp/install-poetry.py

 
