- name: Download Miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/install-miniconda.sh
    checksum: sha256:78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689
    mode: 0755
  register: download_miniconda

- name: Create conda folder
  file:
    path: "{{ conda_dir }}"
    state: directory
    mode: 0755
    recurse: yes
  register: create_conda_dir
  when: download_miniconda.changed

- name: Run the installer
  shell: |
    /tmp/install-miniconda.sh -b -u -p {{ conda_dir }}
    {{ conda_dir }}/bin/conda init zsh
  when: (download_miniconda.changed) and (create_conda_dir.changed)
  register: install_conda

- name: ohmyzsh shows conda env
  shell: "{{ conda_dir }}/bin/conda config --set changeps1 False"

- name: Install Github CLI
  shell: ./bin/conda install -y -c conda-forge gh
  args:
    chdir: "{{ conda_dir }}"

- name: Install add ssh key to gh
  shell: |
    ./bin/gh auth login --with-token {{ github_token }}
    ./bin/gh ssh-key add {{ home_dir }}/.ssh/id_ed25519.pub
  args:
    chdir: "{{ conda_dir }}"
  when: (github_token is defined) and (github_token|length > 0)
  ignore_errors: true

- debug:
    msg: "Not adding SSH key to gh because GH_TOKEN was not found"
  when: (github_token is undefined) or (github_token|length == 0)

- name: Configure pip
  shell: |
    pip config set global.trusted-host 'pypi.org pypi.python.org files.pythonhosted.org'
  register: pip_conf
  failed_when: pip_conf.rc != 0

- name: Install venv (for poetry)
  apt:
    name: python3-venv
    state: present
  become: true

- name: Install poetry
  shell: |
    curl -sSL https://install.python-poetry.org | python3 -
