---

- name: Verify
  hosts: all
  gather_facts: true
  become: false
  roles:
    - { role: shell }
  vars_files: ../../vars/main.yml
  tasks:
    - name: sdkman is installed
      stat:
        path: "{{ sdkman_dir }}/bin/sdkman-init.sh"
      register: has_sdkman
      failed_when: not has_sdkman.stat.exists
    - name: java is on the path
      shell: "{{ shell }} -elc 'java --version'"
      register: java_version
      failed_when: java_version.rc != 0
    - name: sbt is on the path
      shell: "{{ shell }} -elc 'which sbt'"
      register: sbt_installed
      failed_when: sbt_installed.rc != 0
    - name: scala is on the path
      shell: "{{ shell }} -elc 'scala --version'"
      register: scala_version
      failed_when: scala_version.rc != 0

