- name: Python cryptograph
  pip:
    name: cryptography
    state: present

- name: Generate SSH key
  community.crypto.openssh_keypair:
    type: ed25519
    path: "{{ home_dir }}/.ssh/id_ed25519"
    passphrase: "{{ ssh_passphrase }}"
