- name: Install latest zsh
  apt:
    name: zsh
    state: latest
  become: yes

- name: Install oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home_dir }}/.oh-my-zsh"
    depth: 1

- name: Install spaceship prompt
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    depth: 1

- name: link spaceship theme
  file:
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    src: "{{ home_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    state: link

- name: Find zsh
  shell: which zsh
  register: which_zsh
  failed_when: which_zsh.rc != 0
  changed_when: false

- name: Change shell
  become: true
  block:
    - name: Ensure user
      user:
        name: "{{ ansible_user }}"
      register: user
      check_mode: true
      changed_when: false
      failed_when: user.state != "present"

    - name: Change shell to zsh
      user:
        name: "{{ ansible_user }}"
        state: present
        shell: "{{ which_zsh.stdout }}"
