- name: Ensure packages
  become: true
  apt:
    pkg:
      - curl
      - unzip
      - zip
    state: present
    update_cache: true

- name: Ensure dirs
  file:
    path:
      - "{{ download_dir }}"
    recurse: true
    state: directory

- name: Is sdkman already installed
  shell: "{{ shell }} -elc 'sdk --version'"
  register: has_sdkman
  failed_when: false
  changed_when: false

- name: Install sdkman if needed
  when: has_sdkman.rc != 0
  block:
    - name: Download sdkman
      get_url:
        url: "https://get.sdkman.io"
        dest: "{{ download_dir }}/install-sdkman.sh"
        mode: 0755
    - name: Run installer
      shell: "{{ shell }} -elc '{{ download_dir }}/install-sdkman.sh'"

- name: Install Java
  shell: |
    source 
    {{ shell }} -elc 'sdk install java {{ java_version }}'"
  register: java_installed
  changed_when: "'already installed' not in java_installed.stdout"

- name: Install sbt
  shell: "{{ shell }} -elc 'sdk install sbt'"
  register: sbt_installed
  changed_when: "'already installed' not in sbt_installed.stdout"

- name: Install Scala
  shell: "{{ shell }} -elc 'sdk install scala {{ scala_version }}'"
  register: scala_installed
  changed_when: "'already installed' not in scala_installed.stdout"

- name: Remove installer
  file:
    path: "{{ download_dir }}/install-sdkman.sh"
    state: absent
