- name: Has AWS CLI
  become: false
  shell: aws --version
  register: has_aws
  changed_when: false
  failed_when: false

- name: Install AWS
  become: true
  when: has_aws.rc != 0
  vars:
    download_dir: "/tmp"
  block:
    - name: Make sure we have unzip
      apt:
        pkg: unzip
        state: present
    - name: Unzip
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ download_dir }}"
        remote_src: yes
    - name: Install
      shell: ./aws/install
      args:
        chdir: "{{ download_dir }}"

- name: Verify AWS CLI exists
  become: false
  shell: aws --version
  register: check_aws
  failed_when: check_aws.rc != 0
  changed_when: false