- name: Download AWS CLI zip
  become: false
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: 0755
  register: download_awscli

- name: Unzip AWS CLI
  shell: |
    unzip awscliv2.zip
    ./aws/install --update
  args:
    chdir: /tmp
  when: download_awscli.changed

- name: Check AWS CLI
  shell: aws --version
  register: check_aws
  failed_when: check_aws.rc != 0