---

- name: Verify
  hosts: all
  gather_facts: true
  become: false
  roles:
    - { role: shell }
  vars_files: ../../vars/main.yml
  vars:
    ansible_user: "ansible"
  tasks:
    - name: nvm is installed
      shell: "{{ shell }} -elc 'nvm --version'"
      register: has_nvm
      failed_when: has_nvm.rc != 0
    - name: nodejs is on the path
      shell: "{{ shell }} -elc 'nvm install --lts'"
      register: node_installed
      failed_when: "'already installed' not in node_installed.stderr"
