- name: Ensure package required by nvm
  become: true
  apt:
    pkg: curl
    state: present

- name: nvm is installed
  stat:
    path: "{{ nvm_dir }}/nvm.sh"
  check_mode: true
  register: has_nvm

- name: Install nvm
  when: not has_nvm.stat.exists
  block:
    - name: Ensure dirs
      file:
        path:
          - "{{ download_dir }}"
          - "{{ nvm_dir }}"
        state: directory
    - name: Download nvm
      get_url:
        url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
        dest: "{{ download_dir }}/install-nvm.sh"
        mode: 0755
    - name: Run installer
      shell: "{{ download_dir }}/install-nvm.sh"
      args:
        executable: "{{ shell }}"
      environment:
        NVM_DIR: "{{ nvm_dir }}"

- name: Install nodejs
  shell: |
    . $NVM_DIR/nvm.sh
    nvm install --lts
  register: node_installed
  changed_when: "'already installed' not in node_installed.stderr"
  args:
    executable: "{{ shell }}"
  environment:
    NVM_DIR: "{{ nvm_dir }}"

- name: Remove installer
  file:
    path: "{{ download_dir }}/install-nvm.sh"
    state: absent
