- name: has_conda
  shell: conda info --base
  register: conda_info
  changed_when: false
  failed_when: conda_info.rc == 0 and conda_info.stdout != conda_dir
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"

- name: Install conda
  when: conda_info.rc != 0
  block:
  - name: Download Miniconda
    get_url:
      url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest: "{{ download_dir }}/install-miniconda.sh"
      checksum: sha256:78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689
      mode: 0755
  - name: Create conda folder
    file:
      path: "{{ conda_dir }}"
      state: directory
      mode: 0755
      recurse: yes
  - name: Run the installer
    shell: "{{ download_dir }}/install-miniconda.sh -b -u -p {{ conda_dir }}"
    args:
      executable: "{{ shell }}"
  - name: Init conda
    shell: "{{ conda_dir }}/bin/conda init {{ shell }}"
    args:
      executable: "{{ shell }}"

- name: Github CLI
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
  block:
  - name: has_gh
    shell: gh --version
    register: has_gh
    changed_when: false
    failed_when: false
  - name: Install Github CLI
    shell: conda install -y -c conda-forge gh
    when: has_gh.rc != 0

- name: Ensure pip
  become: true
  apt:
    pkg:
      - python3-pip
      - python3-venv
    state: present
    
- name: Configure pip
  shell: pip3 config --user set global.trusted-host 'pypi.org pypi.python.org files.pythonhosted.org'
  register: pip_conf
  failed_when: pip_conf.rc != 0
  changed_when: false

- name: has_poetry
  shell: poetry --version
  register: has_poetry
  failed_when: false
  changed_when: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.HOME }}/.poetry/bin:{{ ansible_env.PATH }}"

- name: Install poetry
  when: has_poetry.rc != 0
  become: false
  block:
    - name: Download poetry
      get_url:
        url: https://install.python-poetry.org
        dest: "{{ download_dir}}/install-poetry.py"
        mode: 0755  
    - name: Run installer
      shell: "python3 {{ download_dir}}/install-poetry.py"
    - name: Remove installer
      file:
        path: "{{ download_dir}}/install-poetry.py"
        state: absent