---
- name: Converge
  hosts: all
  vars:
    ansible_user: "ansible"
    ssh_passphrase: "test"
  roles:
    - { role: ../../roles/common }
    - { role: ../../roles/zsh, tags: [ 'dev', 'zsh' ] }
    - { role: ../../roles/ssh, tags: [ 'dev', 'ssh' ] }
    - { role: ../../roles/python, tags: [ 'dev', 'python' ] }
    - { role: ../../roles/docker, tags: [ 'dev', 'docker' ] }
    - { role: ../../roles/aws, tags: [ 'dev', 'aws' ]}
    - { role: ../../roles/nodejs, tags: [ 'dev', 'js' ] }
    - { role: ../../roles/terraform, tags: [ 'dev', 'tf' ] }
    - { role: ../../roles/jvm, tags: ['dev', 'jvm'] }
  tasks:
    - import_tasks: ../../links.yml