---

- name: Verify
  hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: dotfile
    stat:
      path: "{{ item }}"
    register: dotfile
    failed_when: not dotfile.stat.exists
    with_items:
      - "~/.gitconfig"
      - "~/.zshrc"
      - "~/.emac.d/init.el"