---

- name: Verify
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Has conda
      shell: |
        export PATH=~/miniconda3/bin:$PATH
        conda --version
      register: conda_version
      failed_when: conda_version.rc != 0

    - name: Has gh
      shell: |
        export PATH=~/miniconda3/bin:$PATH
        gh --version
      register: gh_version
      failed_when: gh_version.rc != 0

    - name: Does poetry exist
      shell: |
        export PATH=~/.local/bin:~/.poetry/bin:$PATH
        poetry --version
      register: poetry_version
      failed_when: poetry_version.rc != 0

