---
- name: Link gitconfig
  file:
    src: "{{ links_dir }}/.gitconfig"
    dest: "~/.gitconfig"
    state: link
- name: Emacs init
  block:
    - name: Ensure .emacs.d directory
      file:
        path: "~/.emacs.d"
        state: directory
    - name: Link init.el
      file:
        src: "{{ links_dir }}/.emacs.d/init.el"
        dest: "~/.emacs.d/init.el"
        state: link
- name: Link zshrc
  block:
    - name: has zshrc already
      stat:
        path: "~/.zshrc"
      register: has_zshrc
    - name: backup existing zshrc
      when: has_zshrc.stat.exists and not has_zshrc.stat.islnk
      block:
        - copy:
            remote_src: true
            src: "~/.zshrc"
            dest: "~/zshrc_bak"
        - file:
            path: "~/.zshrc"
            state: absent
    - name: link zshrc
      when: not has_zshrc.stat.exists or not has_zshrc.stat.islnk
      file:
        src: "{{ links_dir }}/.zshrc"
        dest: "~/.zshrc"
        state: link
- name: Configure conda
  shell: conda config --set changeps1 False
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
  args:
    executable: bash
  changed_when: false
