---
- name: Setup dev environment
  gather_facts: true
  hosts: devmachine
  vars_prompt:
    - name: ssh_passphrase
      prompt: Enter your ssh key passphrase?
  vars:
    is_desktop: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"
  pre_tasks:
    - name: hostname
      command: hostname
    - name: user
      command: echo ${USER}
    - debug:
        msg: "Remote user is {{ ansible_user }}"
  roles:
    - { role: common, become: yes }
    - { role: zsh, become: no, tags: [ 'dev', 'zsh' ] }
    - { role: ssh, become: no, tags: [ 'dev', 'ssh' ] }
    - { role: python, become: no, tags: [ 'dev', 'python' ] }
    - { role: docker, become: yes, tags: [ 'dev', 'docker' ] }
    - { role: aws, become: yes, tags: [ 'dev', 'aws' ]}
    - { role: nodejs, become: yes, tags: [ 'dev', 'js' ] }
    - { role: terraform, become: yes, tags: [ 'dev', 'tf' ] }
    - { role: jvm, become: no, tags: ['dev', 'jvm'] }
    - { role: desktop, become: yes, tags: [ 'desktop' ], when: "(is_desktop is defined) and (is_desktop|length>0)"}
  tasks:
    - import_tasks: links.yml