---
- name: Setup dev environment
  gather_facts: true
  hosts: devmachine
  vars_prompt:
    - name: ssh_passphrase
      prompt: Enter your ssh key passphrase?
  vars:
    is_desktop: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"
    links_dir: "{{ playbook_dir }}"
  pre_tasks:
    - name: hostname
      command: hostname
    - name: user
      command: echo ${USER}
    - debug:
        msg: "Remote user is {{ ansible_user }}"
  roles:
    - { role: common }
    - { role: zsh, tags: [ 'dev', 'zsh' ] }
    - { role: ssh, tags: [ 'dev', 'ssh' ] }
    - { role: python, tags: [ 'dev', 'python' ] }
    - { role: docker, tags: [ 'dev', 'docker' ] }
    - { role: aws, tags: [ 'dev', 'aws' ]}
    - { role: nodejs, tags: [ 'dev', 'js' ] }
    - { role: terraform, tags: [ 'dev', 'tf' ] }
    - { role: jvm, tags: ['dev', 'jvm'] }
    - { role: cpp, tags: [ 'dev', 'cpp' ] }
    - { role: desktop, become: yes, tags: [ 'desktop' ],
        when: "(is_desktop is defined) and (is_desktop|length>0)" }
  tasks:
    - import_tasks: links.yml