on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install ansible and molecule
        run: pip install ansible molecule[docker]
      - name: Test nodejs role
        working-directory: "${{ github.repository }}/roles/nodejs"
      - name: Test docker role
        working-directory: "${{ github.repository }}/roles/docker"
        run: molecule --debug -vv test
      - name: Test ssh role
        working-directory: "${{ github.repository }}/roles/ssh"
        run: molecule --debug -vv test
      - name: Test python role
        working-directory: "${{ github.repository }}/roles/python"
        run: molecule --debug -vv test
      - name: Test common role
        working-directory: "${{ github.repository }}/roles/common"
        run: molecule --debug -vv test
      - name: Test AWS role
        working-directory: "${{ github.repository }}/roles/aws"
        run: molecule --debug -vv test
      - name: Test Terraform role
        working-directory: "${{ github.repository }}/roles/terraform"
        run: molecule --debug -vv test
