on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role: [zsh, jvm, nodejs, docker, ssh, python, common, aws, terraform, shell]
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install ansible and molecule
        run: pip install ansible molecule[docker]
      - name: Test ${{ matrix.role }} role
        working-directory: "${{ github.repository }}/ansible/roles/${{ matrix.role }}"
        run: molecule --debug -vv test
