on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Test common role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug --verbose "2"
          molecule_command: test
          molecule_working_dir: '${{ github.repository }}/roles/common'